-- Create default roles if they don't exist
INSERT INTO roles (name, permissions)
VALUES 
  ('MASTER', ARRAY['TODAS_AS_PERMISSOES']),
  ('COLABORADOR', ARRAY['GERENCIAR_USUARIOS', 'EDITAR_MISSOES', 'EDITAR_CATALOGOS_DE_SERVICO']),
  ('USUARIO', ARRAY['EDITAR_MISSOES'])
ON CONFLICT (name) DO NOTHING;
