ALTER TYPE "ENUM_TYPE_DOC" ADD VALUE IF NOT EXISTS 'Passaporte';
ALTER TYPE "ENUM_TYPE_DOC" ADD VALUE IF NOT EXISTS 'Visto';
ALTER TYPE "ENUM_TYPE_DOC" ADD VALUE IF NOT EXISTS 'Vacinas';
ALTER TYPE "ENUM_TYPE_DOC" ADD VALUE IF NOT EXISTS 'Seguros';
ALTER TYPE "ENUM_TYPE_DOC" ADD VALUE IF NOT EXISTS 'Carteira de motorista';
ALTER TYPE "ENUM_TYPE_DOC" ADD VALUE IF NOT EXISTS 'Autorização dos pais (para menores)';
